language: php

services:
    - mysql

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: WITH_COVERAGE=true
    fast_finish: true

before_install:
    - mysql -e 'CREATE DATABASE remg_generator;'

install:
    - composer --prefer-source update

script:
    - vendor/bin/phpunit  -v

after_success:
    - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter; fi
